=== zertex-labs/dmcp/packages/metadata/schemas/food.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "CARROT": {
      "$ref": "#/definitions/food"
    },
    "CHORUS_FRUIT": {
      "$ref": "#/definitions/food"
    },
    "WHEAT": {
      "$ref": "#/definitions/food"
    },
    "SUGAR_CANE": {
      "$ref": "#/definitions/food"
    }
  },
  "required": ["CARROT", "CHORUS_FRUIT", "WHEAT", "SUGAR_CANE"],
  "definitions": {
    "food": {
      "type": "object",
      "properties": {
        "price": {
          "type": "number",
          "minimum": 0.1
        },
        "weight": {
          "type": "integer",
          "minimum": 1
        },
        "probability": {
          "type": "integer",
          "minimum": 0
        },
        "maxItems": {
          "type": "integer",
          "minimum": 1
        },
        "rarityOverwrites": {
          "propertyNames": {
            "$ref": "../enums/rarities.json"
          },
          "additionalProperties": {
            "type": "object",
            "properties": {
              "price": {
                "type": "number",
                "minimum": 0.1
              },
              "probability": {
                "type": "integer",
                "minimum": 0
              },
              "maxItems": {
                "type": "integer",
                "minimum": 1
              },
              "weight": {
                "type": "integer",
                "minimum": 1
              }
            },
            "required": ["price", "probability", "maxItems", "weight"]
          }
        }
      },
      "required": ["price", "probability", "rarityOverwrites", "maxItems", "weight"]
    }
  }
}

=== zertex-labs/dmcp/packages/metadata/food.json
{
  "$schema": "./schemas/food.json",
  "WHEAT": {
    "price": 0.5,
    "probability": 0,
    "maxItems": 50,
    "rarityOverwrites": {},
    "weight": 1
  },
  "CARROT": {
    "price": 0.3,
    "probability": 5,
    "maxItems": 40,
    "rarityOverwrites": {},
    "weight": 2
  },
  "SUGAR_CANE": {
    "price": 0.5,
    "probability": 4,
    "maxItems": 40,
    "rarityOverwrites": {},
    "weight": 5
  },
  "CHORUS_FRUIT": {
    "price": 10,
    "probability": 1,
    "maxItems": 5,
    "weight": 10,
    "rarityOverwrites": {
      "MYTHICAL": {
        "price": 10,
        "probability": 2,
        "maxItems": 5,
        "weight": 10
      },
      "LEGENDARY": {
        "price": 12,
        "probability": 1,
        "maxItems": 10,
        "weight": 10
      }
    }
  }
}
